millenniumFalcon:
  configFile: classpath:millennium-falcon.json
spring:
  datasource:
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: update
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.SecurityAutoConfiguration
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB