name: Backend CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'backend/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'backend/**'
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v3-prerelease
      with:
        arguments: build -x test
  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Test with Gradle
        uses: gradle/gradle-build-action@v3-prerelease
        with:
          arguments: test
          
