name: Frontend CI
on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'frontend/**'
    - '.github/workflows/frontend.yml'
    - '!**.md'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'frontend/**'
    - '.github/workflows/frontend.yml'
    - '!**.md'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 20.x
    defaults:
      run:
        working-directory: 'frontend'
    steps:
    - uses: actions/checkout@v4
    - name: Update Unix enviornment
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev
    - name: Use Node.js ${{env.NODE_VERSION}}
      uses: actions/setup-node@v4
      with:
        node-version: ${{env.NODE_VERSION}}
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
