# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Frontend CI

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]
    paths:
    - 'frontend/**'
  pull_request:
    branches: [ "main" ]
    paths:
    - 'frontend/**'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NODE_VERSION: 16.x
    defaults:
      run:
        working-directory: 'frontend'
    steps:
    - uses: actions/checkout@v3
    - name: Update Unix enviornment
      run: |
        sudo apt-get update
        sudo apt-get install -y libgbm-dev
    - name: Use Node.js $NODE_VERSION
      uses: actions/setup-node@v3
      with:
        node-version: $NODE_VERSION
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
